language: java
install: true
jdk: oraclejdk8
sudo: required

env:
  matrix:
  - TERM=dumb

services:
  - docker

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java8-installer

script: ./gradlew clean build jacocoTestReport jacocoRootMergeReport -S

after_success:
  - ./gradlew :integration-tests:waitForPayaraIntegrationStarted
  - ./gradlew :integration-tests:waitForWildflyIntegrationStarted
  - ./gradlew :integration-tests:waitForTomEEIntegrationStarted
  - ./gradlew coveralls